## Q1. Pearson correlation coefficient is a measure of the linear relationship between two variables. Suppose you have collected data on the amount of time students spend studying for an exam and their final exam scores. Calculate the Pearson correlation coefficient between these two variables and interpret the result.

In [2]:
# Import those libraries
import pandas as pd
from scipy.stats import pearsonr

import numpy as np

df= pd.DataFrame({
     "study_time":[26,23,20,29],
     "score":[55, 60, 65, 52]
    
})

# Convert dataframe into series
list1 = df['study_time']
list2 = df['score']

print(df)

# Apply the pearsonr()
corr, _ = pearsonr(list1, list2)
print('Pearsons correlation: %.3f' % corr)

coef=np.corrcoef(list1, list2)

print(coef)


   study_time  score
0          26     55
1          23     60
2          20     65
3          29     52
Pearsons correlation: -0.994
[[ 1.         -0.99385869]
 [-0.99385869  1.        ]]


In [3]:
df.corr(method='pearson')

study_time     score
study_time    1.000000 -0.993859
score        -0.993859  1.000000

## Q2. Spearman's rank correlation is a measure of the monotonic relationship between two variables. Suppose you have collected data on the amount of sleep individuals get each night and their overall job satisfaction level on a scale of 1 to 10. Calculate the Spearman's rank correlation between these two variables and interpret the result.

In [15]:
import pandas as pd

df= pd.DataFrame({
     "individual _amount":[30,21,26,25,24,22,30,21,28,25],
     "satisfaction_level":[9,5,7,8,7,9,6,7,8,5]
})

In [16]:
df

individual _amount  satisfaction_level
0                  30                   9
1                  21                   5
2                  26                   7
3                  25                   8
4                  24                   7
5                  22                   9
6                  30                   6
7                  21                   7
8                  28                   8
9                  25                   5

In [18]:
df.corr(method='spearman')

individual _amount  satisfaction_level
individual _amount            1.000000            0.237519
satisfaction_level            0.237519            1.000000

## Q3. Suppose you are conducting a study to examine the relationship between the number of hours of exercise per week and body mass index (BMI) in a sample of adults. You collected data on both variables for 50 participants. Calculate the Pearson correlation coefficient and the Spearman's rank correlation between these two variables and compare the results.

In [15]:
import pandas as pd
import numpy as np

df= pd.DataFrame({
    "Hour/s":np.random.randint(1,25,size=50),   ## the number of hours of exercise per week
    "BMI":np.random.randint(30,60,size=50)
   
    
})
    

In [16]:
df.head()

Hour/s  BMI
0      22   51
1       9   58
2       8   48
3      24   43
4      11   36

In [17]:
## spearman rank correlation
df.corr(method='spearman')

Hour/s       BMI
Hour/s  1.000000 -0.230178
BMI    -0.230178  1.000000

## Q4. A researcher is interested in examining the relationship between the number of hours individuals spend watching television per day and their level of physical activity. The researcher collected data on both variables from a sample of 50 participants. Calculate the Pearson correlation coefficient between these two variables.

In [66]:
import pandas as pd
import numpy as np

df= pd.DataFrame({
    "Hour/s":np.random.randint(1,5,size=50),   ## the number of hours individuals spend watching television per day
    "activity":np.random.randint(0,3,size=50)    
   
    
})
    

In [67]:
df.head()

Hour/s  activity
0       4         1
1       2         2
2       2         1
3       2         0
4       4         0

In [68]:
# Import those libraries
import pandas as pd
from scipy.stats import pearsonr

import numpy as np

df= pd.DataFrame({
    "Hour/s":np.random.randint(1,5,size=50),   ## the number of hours individuals spend watching television per day
    "activity":np.random.randint(0,3,size=50)    
   
    
})



In [69]:
df.head()

Hour/s  activity
0       1         2
1       4         1
2       1         1
3       3         2
4       1         1

In [70]:
# Convert dataframe into series
list1 = df['Hour/s']
list2 = df['activity']

df.head()

# Apply the pearsonr()
corr, _ = pearsonr(list1, list2)
print('Pearsons correlation: %.3f' % corr)

coef=np.corrcoef(list1, list2)

print(coef)

Pearsons correlation: -0.190
[[ 1.         -0.18976652]
 [-0.18976652  1.        ]]


In [71]:
df.corr(method='pearson')

Hour/s  activity
Hour/s    1.000000 -0.189767
activity -0.189767  1.000000

## Q5. A survey was conducted to examine the relationship between age and preference for a particular brand of soft drink. The survey results are shown below:

In [72]:
# Import those libraries
import pandas as pd
from scipy.stats import pearsonr

import numpy as np

df= pd.DataFrame({
  "Age(Years)" :[25,42 ,37,19,31,28],
    "Soft_drink_Preference":["Coke","Pepsi","Mountain dew","Coke","Pepsi","Coke"]
    
})



In [73]:
df

Age(Years) Soft_drink_Preference
0          25                  Coke
1          42                 Pepsi
2          37          Mountain dew
3          19                  Coke
4          31                 Pepsi
5          28                  Coke

In [74]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [75]:
a=lbl_encoder.fit_transform(df[['Soft_drink_Preference']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [76]:
a

array([0, 2, 1, 0, 2, 0])

In [77]:
df['Soft_drink_Preference']=a

In [78]:
df

Age(Years)  Soft_drink_Preference
0          25                      0
1          42                      2
2          37                      1
3          19                      0
4          31                      2
5          28                      0

In [79]:
list1 = df['Age(Years)']
list2 = df['Soft_drink_Preference']

df.head()

# Apply the pearsonr()
corr, _ = pearsonr(list1, list2)
print('Pearsons correlation: %.3f' % corr)

coef=np.corrcoef(list1, list2)

print(coef)

Pearsons correlation: 0.769
[[1.         0.76917514]
 [0.76917514 1.        ]]


In [81]:
df.corr(method='pearson')

Age(Years)  Soft_drink_Preference
Age(Years)               1.000000               0.769175
Soft_drink_Preference    0.769175               1.000000

In [82]:
## spearman rank correlation
df.corr(method='spearman')

Age(Years)  Soft_drink_Preference
Age(Years)               1.000000               0.833238
Soft_drink_Preference    0.833238               1.000000

## Q6. A company is interested in examining the relationship between the number of sales calls made per day and the number of sales made per week. The company collected data on both variables from a sample of 30 sales representatives. Calculate the Pearson correlation coefficient between these two variables.

In [83]:
# Import those libraries
import pandas as pd
from scipy.stats import pearsonr

import numpy as np

df= pd.DataFrame({
    "call/s":np.random.randint(1,10,size=30),   ## the number of sales calls made per day
    "sales":np.random.randint(15,30,size=30)   ## the number of sales made per week 
   
    
})



In [84]:
df.head()

call/s  sales
0       1     29
1       4     22
2       2     18
3       4     23
4       3     20

In [85]:
list1 = df['call/s']
list2 = df['sales']

df.head()

# Apply the pearsonr()
corr, _ = pearsonr(list1, list2)
print('Pearsons correlation: %.3f' % corr)

coef=np.corrcoef(list1, list2)

print(coef)

Pearsons correlation: 0.024
[[1.         0.02394844]
 [0.02394844 1.        ]]


In [86]:
df.corr(method='pearson')

call/s     sales
call/s  1.000000  0.023948
sales   0.023948  1.000000