In [2]:
## Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

## Yes, there is a difference in both the data type of variables list_ and array_list.

In [8]:
type(list_)

list

In [6]:
type(array_list)

numpy.ndarray

## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [15]:
for i in list_:
    print(i)
    print(type(i))

1
<class 'str'>
2
<class 'str'>
3
<class 'str'>
4
<class 'str'>
5
<class 'str'>


In [16]:
for j in array_list:
    print(j)
    print(type(j))

1
<class 'numpy.str_'>
2
<class 'numpy.str_'>
3
<class 'numpy.str_'>
4
<class 'numpy.str_'>
5
<class 'numpy.str_'>


In [23]:
## Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [24]:
array_list

array([1, 2, 3, 4, 5])

In [25]:
type(list_)

list

In [26]:
type(array_list)

numpy.ndarray

In [27]:
for i in list_:
    print(i)
    print(type(i))

1
<class 'str'>
2
<class 'str'>
3
<class 'str'>
4
<class 'str'>
5
<class 'str'>


In [28]:
for j in array_list:
    print(j)
    print(type(j))

1
<class 'numpy.int64'>
2
<class 'numpy.int64'>
3
<class 'numpy.int64'>
4
<class 'numpy.int64'>
5
<class 'numpy.int64'>


## type of every element in the list_  is still string but the type of every element in the array_list has been changed to integer value.

In [29]:
## Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [30]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

## Q4. Write a code to find the following characteristics of variable, num_array:
## (i) shape
## (ii) size

In [31]:
num_array.shape

(2, 3)

In [32]:
num_array.size

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
## [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [33]:
# Python Program to create array with all zeros 
import numpy as np 
    
zero = np.zeros([3, 3], dtype = int)  
print("\nMatrix  zero: \n", zero) 


Matrix  zero: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [34]:
zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
zero.shape

(3, 3)

In [36]:
zero.size

9

## Q6. Create an identity matrix of shape (5,5) using numpy functions?
## [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [37]:

import numpy as np

e = np.identity(5, dtype = float)
print("Matrix e : \n", e)

Matrix e : 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
