## Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you might choose one over the other.

## Ordinal encoding is a technique to transform categorical features into a numerical format. In ordinal encoding, labels are translated to numbers based on their ordinal relationship to one another.

## Label Encoding makes it possible for algorithms to interpret and comprehend the data by giving each category within a variable a distinct number. Consider a dataset where the "Gender" column has two categories: "Male" and "Female." "Male" might be rendered as 0, and "Female" as 1, after Label Encoding.

## OrdinalEncoder can be used to encode temperature categories (cold, warm, hot) as 0, 1, 2, preserving their order. LabelEncoder can be used to encode color categories (red, blue, green) as 0, 1, and 2, without considering any order.

In [1]:
## ordinal encoding
from sklearn.preprocessing import OrdinalEncoder

In [3]:
## dataframe with an ordinal variable
import pandas as pd
df= pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [4]:
df

size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [5]:
## create an instance of ordinalecoder and then fit_transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [6]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [7]:
encoder.transform([['small']])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])

## Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in a machine learning project.

## Target-guided ordinal encoding involves replacing the categories in the categorical variable with ordinal numbers that are based on the relationship between the category and the target variable.

## Let’s say we have a dataset that contains information about employees at a company. One of the variables in the dataset is “job level”, which is a categorical variable with four categories: junior, intermediate, senior, and executive. The target variable in this case is the employee’s salary.

## To encode the “job level” variable using target-guided ordinal encoding, we would first calculate the mean salary for each job level category. Let’s say the mean salaries are as follows:

## Junior: $40,000
## Intermediate: $60,000
## Senior: $80,000
## Executive: $120,000
## Next, we would sort the job levels based on their mean salaries, from lowest to highest. Then, we would assign ordinal numbers to each job level based on their rank:

## Junior: 1
## Intermediate: 2
## Senior: 3
## Executive: 4
## Now, we have encoded the “job level” variable using target-guided ordinal encoding, and we can use these ordinal numbers as input features in a machine learning model to predict employee salaries. This encoding technique takes into account the relationship between the job level categories and the target variable, which can help improve the accuracy of the model.



## Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

## Covariance is a measure of the relationship between two random variables and to what extent, they change together.
## Covariance is an important statistical metric for comparing the relationships between multiple variables. In investing, covariance is used to identify assets that can help diversify a portfolio.

## Covariance is calculated by analyzing at-return surprises (standard deviations from the expected return) or multiplying the correlation between the two random variables by the standard deviation of each variable.

In [6]:
import seaborn as sns
import numpy as np

In [7]:
df=sns.load_dataset('healthexp')

In [8]:
df.head()

Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [9]:
df.cov()

/tmp/ipykernel_592/1545644723.py:1: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.cov()


Year  Spending_USD  Life_Expectancy
Year               201.098848  2.571883e+04        41.915454
Spending_USD     25718.827373  4.817761e+06      4166.800912
Life_Expectancy     41.915454  4.166801e+03        10.733902

## Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium, large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library. Show your code and explain the output.

In [13]:
import pandas as pd

df= pd.DataFrame({
    'Color': ['red', 'green', 'blue'],
     'Size':['small', 'medium','large'],
    'Material':['wood', 'metal', 'plastic']
})

In [14]:
df

Color    Size Material
0    red   small     wood
1  green  medium    metal
2   blue   large  plastic

In [5]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [16]:
lbl_encoder.fit_transform(df[['Color']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 1, 0])

In [17]:
lbl_encoder.fit_transform(df[['Size']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 1, 0])

In [18]:
lbl_encoder.fit_transform(df[['Material']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1])

## By using label encoding we labeled the things between 0 to 2.

## Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education level. Interpret the results.

In [1]:
import pandas as pd

df= pd.DataFrame({
    'Age': [25,24,26,21,22],
     'Income':[25000,30000,20000,18000,23000],
    'Education level':['bechlor', 'masters', 'bechlor','masters','MBA']
})

In [2]:
df

Age  Income Education level
0   25   25000         bechlor
1   24   30000         masters
2   26   20000         bechlor
3   21   18000         masters
4   22   23000             MBA

In [8]:
df.cov()

/tmp/ipykernel_109/1545644723.py:1: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.cov()


Age      Income
Age        4.3      2850.0
Income  2850.0  21700000.0

## Q6. You are working on a machine learning project with a dataset containing several categorical variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD), and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for each variable, and why?

## Consider a dataset where the "Gender" column has two categories: "Male" and "Female." "Male" might be rendered as 1, and "Female" as 0, after Label Encoding.

## In Ordinal encoding, each unique category value is assigned an integer value. For example,"High School" is assigned 0, "Bachelors" is assigned 1, "Masters" is assigned 2, and "PHD" is assigned 3.

## After applying label encoding to Employment Status column the three different categories are mapped into integers 2:Unemployed, 1:Part-Time, 0:Full-Time

In [2]:
import pandas as pd

df= pd.DataFrame({
      "Gender": ["Male","Female","Male","Female"], 
     "Education Level":["High Schoo","Bachelor's","Master's","PhD"],
    "Employment Status":["Unemployed","Part-Time","Full-Time","Part-Time"]
})
   

In [3]:
df

Gender Education Level Employment Status
0    Male      High Schoo        Unemployed
1  Female      Bachelor's         Part-Time
2    Male        Master's         Full-Time
3  Female             PhD         Part-Time

In [4]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [5]:
lbl_encoder.fit_transform(df[['Employment Status']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 1, 0, 1])

In [6]:
lbl_encoder.fit_transform(df[['Gender']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 1, 0])

In [8]:
## ordinal encoding
from sklearn.preprocessing import OrdinalEncoder

In [9]:
## create an instance of ordinalecoder and then fit_transform
encoder=OrdinalEncoder(categories=[["High Schoo","Bachelor's","Master's","PhD"]])

In [10]:
encoder.fit_transform(df[['Education Level']])

array([[0.],
       [1.],
       [2.],
       [3.]])

## Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/ East/West). Calculate the covariance between each pair of variables and interpret the results.

In [4]:
import pandas as pd

df= pd.DataFrame({
     "Temperature":[26,23,20,29],
     "Humidity":[55, 60, 65, 52],
     "Weather Condition": ["Sunny","Cloudy","Rainy","Sunny"],
     "Wind Direction":["North", "South", "East", "West"]
})

In [5]:
df

Temperature  Humidity Weather Condition Wind Direction
0           26        55             Sunny          North
1           23        60            Cloudy          South
2           20        65             Rainy           East
3           29        52             Sunny           West

In [6]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [9]:
a=lbl_encoder.fit_transform(df[['Weather Condition']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
b=lbl_encoder.fit_transform(df[['Wind Direction']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
df['Weather Condition']=a

In [12]:
df['Wind Direction']=b

In [13]:
df

Temperature  Humidity  Weather Condition  Wind Direction
0           26        55                  2               1
1           23        60                  0               2
2           20        65                  1               0
3           29        52                  2               3

In [14]:
df.cov()

Temperature   Humidity  Weather Condition  Wind Direction
Temperature               15.0 -22.000000           2.500000        4.000000
Humidity                 -22.0  32.666667          -3.666667       -5.666667
Weather Condition          2.5  -3.666667           0.916667        0.166667
Wind Direction             4.0  -5.666667           0.166667        1.666667